# Apex - taskbar-pinnable launcher.  (ASCII only: PS 5.1 reads this file as ANSI.)
#
# The dev launch shape is "generic electron.exe + app folder as an argument".
# Windows pins the *executable*, drops the argument, and you get bare Electron.
# This script gives Apex its own executable identity WITHOUT a build step:
#
#   1. Apex.exe        - a copy of electron.exe (same folder, so it finds its DLLs/paks)
#   2. resources/app/  - a loader Electron picks up automatically, which requires
#                        the LIVE source tree. No bundling: edit, restart, done.
#   3. brand icon stamped into Apex.exe (rcedit), so a pin from the running
#      window carries our icon, not Electron's.
#   4. Apex.lnk repointed at Apex.exe with no arguments.
#
# Re-run after any `npm install` - npm replaces node_modules and takes
# Apex.exe + resources/app with it. Idempotent; safe to run any time.
#
# Rollback: delete Apex.exe + resources/app, point Apex.lnk back at electron.exe
# with the app folder as its argument.

$ErrorActionPreference = 'Stop'

$appDir  = Resolve-Path (Join-Path $PSScriptRoot '..')
$distDir = Join-Path $appDir 'node_modules\electron\dist'
$srcExe  = Join-Path $distDir 'electron.exe'
$apexExe = Join-Path $distDir 'Apex.exe'
$resApp  = Join-Path $distDir 'resources\app'
# The icon ships in this repository.
$icon    = Join-Path $appDir 'assets\apex.ico'
if (-not (Test-Path $icon)) {
  throw "Apex icon not found at $icon"
}
$lnk     = Join-Path ([Environment]::GetFolderPath('Desktop')) 'Apex.lnk'

if (-not (Test-Path $srcExe)) {
  throw "electron.exe not found at $srcExe (run npm install in the repo root first)"
}

# 1. Apex.exe - refresh if missing or older than the electron.exe it copies.
$needCopy = -not (Test-Path $apexExe) -or
            ((Get-Item $apexExe).LastWriteTime -lt (Get-Item $srcExe).LastWriteTime)
if ($needCopy) {
  Write-Host 'Copying electron.exe -> Apex.exe ...'
  Copy-Item $srcExe $apexExe -Force
} else {
  Write-Host 'Apex.exe already current.'
}

# 2. resources/app - the loader. Electron prefers resources/app over its
#    default_app.asar, so Apex.exe with zero arguments starts OUR app.
#    __dirname inside the real main.js still resolves to the repo's main/ folder,
#    so every relative path (renderer, theme.json, state/, seatconfig) is intact.
New-Item -ItemType Directory -Force -Path $resApp | Out-Null

$mainJs = (Join-Path $appDir 'main\main.js') -replace '\\', '/'

$pkg = @"
{
  "name": "apex",
  "productName": "Apex",
  "version": "0.1.0",
  "private": true,
  "description": "Apex launcher stub - loads the live source tree (see scripts/make-launcher.ps1).",
  "main": "loader.js"
}
"@
$pkg | Set-Content -Path (Join-Path $resApp 'package.json') -Encoding ascii

$loader = @"
// Generated by scripts/make-launcher.ps1 - do not edit.
// Apex.exe's entry point: hand off to the live source tree. Nothing is copied
// here, so editing the repo and restarting is still the whole loop.
require('$mainJs');
"@
$loader | Set-Content -Path (Join-Path $resApp 'loader.js') -Encoding ascii

Write-Host "Loader written -> $resApp"

# 3. Icon + version strings. rcedit is a dev-time tool, installed to TEMP so it
#    never becomes a project dependency. (The npm package ships the binary but
#    declares no CLI entry, so `npx rcedit` cannot work - call the exe directly.)
#    If this fails (offline, exe locked), Apex.exe keeps Electron's icon and the
#    shortcut still shows ours: cosmetic degradation, not a failure.
$rcDir = Join-Path $env:TEMP 'apex-rcedit'
$rcExe = Join-Path $rcDir 'node_modules\rcedit\bin\rcedit-x64.exe'
if (-not (Test-Path $rcExe)) {
  Write-Host 'Fetching rcedit (dev tool, TEMP only) ...'
  New-Item -ItemType Directory -Force -Path $rcDir | Out-Null
  Push-Location $rcDir
  & npm.cmd install rcedit --no-save --no-audit --no-fund | Out-Null
  Pop-Location
}
if (Test-Path $rcExe) {
  Write-Host 'Stamping brand icon into Apex.exe ...'
  & $rcExe "$apexExe" --set-icon "$icon" `
      --set-version-string 'FileDescription' 'Apex' `
      --set-version-string 'ProductName' 'Apex' `
      --set-version-string 'CompanyName' 'Apex'
  if ($LASTEXITCODE -ne 0) {
    Write-Warning "rcedit failed (exit $LASTEXITCODE). Apex.exe keeps Electron's icon; re-run later."
  } else {
    Write-Host 'Icon stamped.'
  }
} else {
  Write-Warning 'rcedit unavailable. Apex.exe keeps Electron icon; re-run this script when online.'
}

# 4. Shortcut -> Apex.exe, no arguments.
$sh = New-Object -ComObject WScript.Shell
$s  = $sh.CreateShortcut($lnk)
$s.TargetPath       = $apexExe
$s.Arguments        = ''
$s.WorkingDirectory = $distDir
$s.IconLocation     = "$icon,0"
$s.Description      = 'Apex - the one window'
$s.Save()
Write-Host "Shortcut updated -> $lnk"

Write-Host ''
Write-Host 'Done. Launch Apex, right-click its taskbar button, Pin to taskbar.'
